plane-enterprise:
  fullnameOverride: infra-plane
  license:
    licenseDomain: plane.127.0.0.1.sslip.io
  env:
    web_url: http://plane.127.0.0.1.sslip.io:32080
    storageClass: hostpath
  planeVersion: v2.4.0
  ingress:
    enabled: true
    ingressClass: kong
  services:
    worker:
      memoryLimit: 2Gi
      memoryRequest: 512Mi
      cpuLimit: 1000m
      cpuRequest: 250m
plane-event-bridge:
  fullnameOverride: infra-plane-event-bridge-api
  image:
    repository: admin/plane-event-bridge
    tag: latest
  ingress:
    enabled: true
    className: kong
    annotations:
      konghq.com/strip-path: "true"
    hosts:
      - host: ""
        paths:
          - path: /plane-event-bridge-api
            pathType: Prefix
  env:
    - name: PLANE_API_URL
      value: http://plane.127.0.0.1.sslip.io:32080/api/v1
    - name: PLANE_API_KEY
      value: plane_api_0b0f277556a74289aeb802e3a581f937
    - name: PLANE_PROJECT_INTERNAL_ID
      value: 47cb2524-ef10-4959-9dde-a93e81824dca
    - name: PLANE_WORKSPACE
      value: init-build
    - name: PLANE_PROJECT_ID
      value: PA
