plane-enterprise:
  fullnameOverride: infra-plane
  license:
    licenseDomain: plane.127.0.0.1.sslip.io
  planeVersion: v2.4.0
  ingress:
    enabled: true
    ingressClass: kong
  env:
    storageClass: hostpath
  services:
    worker:
      memoryLimit: 2Gi
      memoryRequest: 512Mi
      cpuLimit: 1000m
      cpuRequest: 250m
