{{- if and .Values.services.email_service.enabled .Values.env.email_service_envs.smtp_domain }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "plane.fullname" . }}-mail-tls-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.env.email_service_envs.smtp_domain | quote }}

  issuerRef:
    name: {{ include "plane.fullname" . }}-cert-issuer
  secretName: {{ (include "plane.fullname" .) }}-mail-tls-secret
---
{{- end }}