apiVersion: v2
name: infra
description: A Helm chart for Personal assistant infrastructure
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: plane-enterprise
    version: 2.3.2
  - name: plane-event-bridge
    version: 0.1.0
