apiVersion: v2
name: infra
description: A Helm chart Pranci bot infrastructure
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.16.0"
dependencies:
  - name: event-dispatcher
    version: 1.0.0-SNAPSHOT
    repository: file://../../event-dispatcher/deploy/chart
  - name: platform-gateway
    version: 1.0.0-SNAPSHOT
    repository: file://../../platform-gateway/deploy/chart
  - name: event-dispatcher-topic-provisioner
    version: 1.0.0-SNAPSHOT
    repository: file://../../event-dispatcher-topic-provisioner/deploy/chart
  - name: persistent-storage
    version: 1.0.0-SNAPSHOT
    repository: file://../../persistent-storage/deploy/chart