apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plane-pv-pgdb
  labels:
    app: plane-pgdb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostpath }}/.plane-data/pgdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plane-pv-redis
  labels:
    app: plane-redis
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostpath }}/.plane-data/redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plane-pv-rabbitmq
  labels:
    app: plane-rabbitmq
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostpath }}/.plane-data/rabbitmq
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plane-pv-minio
  labels:
    app: plane-minio
spec:
  capacity:
    storage: 5Gi   # ⚠️ fix to match PVC default
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostpath }}/.plane-data/minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plane-pv-monitor
  labels:
    app: plane-monitor
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostpath }}/.plane-data/monitor