{{- if .Values.global.useSharedConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-shared-config" .Release.Name }}
  labels:
    {{- include "charrt.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-event-dispatcher:9092"
  KAFKA_PRODUCER_RETRIES: "3"
{{- end }}

