apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-kafka-topic-bootstrap
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-topics
          image: docker.io/apache/kafka:latest

          envFrom:
            - configMapRef:
                name: {{include "chart.sharedConfig" .}}

          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Waiting for Kafka at $KAFKA_BOOTSTRAP_SERVERS..."

              until /opt/kafka/bin/kafka-broker-api-versions.sh \
                --bootstrap-server "$KAFKA_BOOTSTRAP_SERVERS" >/dev/null 2>&1; do
                echo "Kafka not ready yet, retrying..."
                sleep 5
              done

              echo "Kafka is ready!"

              echo "Creating topic..."

              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server "$KAFKA_BOOTSTRAP_SERVERS" \
                --create --if-not-exists \
                --topic life-style-tracking \
                --partitions 2 \
                --replication-factor 1