apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "plane.fullname" . }}-api-migrate-{{ now | date "20060102-150405" }}
  {{- include "plane.labelsAndAnnotations" .Values.services.api }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-api-migrate
      annotations:
        timestamp: {{ now | quote }}
    spec:
      {{- include "plane.podScheduling" .Values.services.api }}
      containers:
        - name: {{ include "plane.fullname" . }}-api-migrate
          image: {{ .Values.services.api.image | default "artifacts.plane.so/makeplane/backend-commercial" }}:{{ .Values.planeVersion }}
          command:
            - ./bin/docker-entrypoint-migrator.sh
          imagePullPolicy: {{ .Values.services.api.pullPolicy | default "Always" }}
          envFrom:
            - configMapRef:
                name: {{ include "plane.fullname" . }}-app-vars
                optional: false
            - secretRef:
                name: {{ if not (empty .Values.external_secrets.app_env_existingSecret) }}{{ .Values.external_secrets.app_env_existingSecret }}{{ else }}{{ (include "plane.fullname" .) }}-app-secrets{{ end }}
                optional: false
            - secretRef:
                name: {{ if not (empty .Values.external_secrets.doc_store_existingSecret) }}{{ .Values.external_secrets.doc_store_existingSecret }}{{ else }}{{ (include "plane.fullname" .) }}-doc-store-secrets{{ end }}
                optional: false
            - secretRef:
                name: {{ if not (empty .Values.external_secrets.opensearch_existingSecret) }}{{ .Values.external_secrets.opensearch_existingSecret }}{{ else }}{{ (include "plane.fullname" .) }}-opensearch-secrets{{ end }}
                optional: false
          {{- if .Values.services.silo.enabled }}
            - secretRef:
                name: {{ if not (empty .Values.external_secrets.silo_env_existingSecret) }}{{ .Values.external_secrets.silo_env_existingSecret }}{{ else }}{{ (include "plane.fullname" .) }}-silo-secrets{{ end }}
                optional: false
          {{- end }}
        {{- if .Values.extraEnv }}
          env:
          {{- toYaml .Values.extraEnv | nindent 10 }}
        {{- end }}
      restartPolicy: OnFailure
      serviceAccount: {{ (include "plane.fullname" .) }}-srv-account
      serviceAccountName: {{ (include "plane.fullname" .) }}-srv-account
---