{{- if .Values.services.redis.local_setup }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "plane.fullname" . }}-redis
  labels:
    app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-redis
spec:
  type: ClusterIP
  {{- if not .Values.services.redis.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
  ports:
    - name: redis-{{ .Values.services.redis.servicePort }}
      port: {{ .Values.services.redis.servicePort }}
      protocol: TCP
      targetPort: 6379
  selector:
    app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-redis
---

# REDIS WORKLOAD

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "plane.fullname" . }}-redis-wl
  {{- include "plane.labelsAndAnnotations" .Values.services.redis }}
spec:
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-redis
  serviceName: {{ (include "plane.fullname" .) }}-redis
  template:
    metadata:
      labels:
        app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-redis
    spec:
      {{- include "plane.podScheduling" .Values.services.redis }}
      containers:
        - image: {{ .Values.services.redis.image }}
          imagePullPolicy: {{ .Values.services.redis.pullPolicy | default "IfNotPresent" }}
          name: {{ include "plane.fullname" . }}-redis
          stdin: true
          tty: true
        {{- if .Values.extraEnv }}
          env:
          {{- toYaml .Values.extraEnv | nindent 10 }}
        {{- end }}
          volumeMounts:
            - mountPath: /data
              name: pvc-{{ include "plane.fullname" . }}-redis-vol
              subPath: ''
      serviceAccount: {{ (include "plane.fullname" .) }}-srv-account
      serviceAccountName: {{ (include "plane.fullname" .) }}-srv-account
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        namespace: {{ .Release.Namespace }}
        name: pvc-{{ include "plane.fullname" . }}-redis-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.services.redis.volumeSize | default "1Gi" | quote }}
        storageClassName: {{ .Values.env.storageClass | quote }}
        volumeMode: Filesystem

{{- end }}