apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-server.fullname" . }}
  labels:
    {{- include "kafka-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: internal
      port: {{ .Values.service.ports.internal }}
      targetPort: internal

    - name: controller
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
  selector:
    {{- include "kafka-server.selectorLabels" . | nindent 4 }}
