apiVersion: v2
appVersion: 2.5.3
description:
  Meet Plane. An Enterprise software development tool to manage issues,
  sprints, and product roadmaps with peace of mind.
home: https://plane.so/
icon: https://plane.so/favicon/favicon-32x32.png
name: plane-enterprise
sources:
  - https://github.com/makeplane/plane-ee
type: application
version: 2.3.2
