{{- if .Values.services.outbox_poller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "plane.fullname" . }}-outbox-poller-wl
  {{- include "plane.labelsAndAnnotations" .Values.services.outbox_poller }}
spec:
  replicas: {{ .Values.services.outbox_poller.replicas | default 1}}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-outbox-poller
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ (include "plane.fullname" .) }}-outbox-poller
      annotations:
        timestamp: {{ now | quote }}
    spec:
      {{- include "plane.podScheduling" .Values.services.outbox_poller }}
      containers:
        - name: {{ include "plane.fullname" . }}-outbox-poller
          imagePullPolicy: Always
          image: {{ .Values.services.api.image | default "artifacts.plane.so/makeplane/backend-commercial" }}:{{ .Values.planeVersion }}
          stdin: true
          tty: true
          resources:
            requests:
              memory: {{ .Values.services.outbox_poller.memoryRequest  | default "1000Mi" | quote }}
              cpu: {{ .Values.services.outbox_poller.cpuRequest | default "500m" | quote}}
            limits:
              memory: {{ .Values.services.outbox_poller.memoryLimit  | default "1000Mi" | quote }}
              cpu: {{ .Values.services.outbox_poller.cpuLimit | default "500m" | quote}}
          command:
            - ./bin/docker-entrypoint-outbox-poller.sh
          envFrom:
            - configMapRef:
                name: {{ include "plane.fullname" . }}-outbox-poller-vars
                optional: false
            - configMapRef:
                name: {{ include "plane.fullname" . }}-app-vars
                optional: false
            - secretRef:
                name: {{ if not (empty .Values.external_secrets.app_env_existingSecret) }}{{ .Values.external_secrets.app_env_existingSecret }}{{ else }}{{ (include "plane.fullname" .) }}-app-secrets{{ end }}
                optional: false
        {{- if .Values.extraEnv }}
          env:
          {{- toYaml .Values.extraEnv | nindent 10 }}
        {{- end }}

      serviceAccount: {{ (include "plane.fullname" .) }}-srv-account
      serviceAccountName: {{ (include "plane.fullname" .) }}-srv-account
{{- end }}