plane.api-url=http://plane.127.0.0.1.sslip.io:32080/api/v1
plane.api-key=plane_api_0b0f277556a74289aeb802e3a581f937
plane.project-internal-id=47cb2524-ef10-4959-9dde-a93e81824dca
plane.workspace=init-build
plane.project-id=PA
# Below are config to work with quarkus-container-image-docker
quarkus.container-image.group=admin
quarkus.container-image.name=plane-event-bridge
quarkus.container-image.tag=latest
quarkus.container-image.build=true